# -*- coding: utf-8 -*-
"""LCF_5900_Repository

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v526lUwE4IiHkLzKYYCgP_yDGselq44Y
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf

# --- Configurações de Inicialização e Estilo ---
# Configuração de fontes (equivalente ao extrafont)
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['DejaVu Sans Condensed', 'Arial', 'sans-serif']
plt.rcParams['font.size'] = 14

# Definição de Cores e Padrões
cores = ["#9e2943", "#0a6c69", "#75a741", "#d18525", "#d86c67", "#5ab5b2"]
eixo_x_labels = ["Control", "Bonito", "Pratápolis", "Catalão", "Arraias", "Registro",
                  "ERCP", "Morocco", "Algeria", "Bayovar", "TSP", "Bonechar"]

# --- Carregamento dos Dados ---
raw_url = "https://raw.githubusercontent.com/jmalonso55/fosfatos/refs/heads/main/Artigo_fosfatos.csv"
dados = pd.read_csv(raw_url, sep=",")[cite: 5]

# Organizando dados e definindo categorias ordenadas (equivalente ao factor ordered)
cult_levels = ["Primeiro", "Segundo", "Acumulado"][cite: 5]
trat_levels = ["Controle", "Bonito", "Pratápolis", "Catalão", "Arraias", "Registro",
               "Digestato", "Marrocos", "Argélia", "Bayóvar", "STP", "BoneChar"][cite: 5]

dados['cult'] = pd.Categorical(dados['cult'], categories=cult_levels, ordered=True)[cite: 5]
dados['trat'] = pd.Categorical(dados['trat'], categories=trat_levels, ordered=True)[cite: 5]

# --- Funções Customizadas ---

def pressupostos(df, y_var, x_var):
    """Verifica pressupostos de Normalidade e Homocedasticidade para ANOVA"""
    # Ajuste do modelo linear (ANOVA)
    formula = f"{y_var} ~ C({x_var})"
    model = smf.ols(formula, data=df).fit()
    residuals = model.resid

    # Teste de Normalidade (Shapiro-Wilk)
    shapiro_stat, shapiro_p = stats.shapiro(residuals)[cite: 5]
    print(f"\n--- Teste de Shapiro-Wilk ({y_var}) ---")
    print(f"Estatística: {shapiro_stat:.4f}, p-value: {shapiro_p:.4e}")[cite: 5]

    # Teste de Homocedasticidade (Bartlett)
    grupos = [group[y_var].values for name, group in df.groupby(x_var)]
    bartlett_stat, bartlett_p = stats.bartlett(*grupos)[cite: 5]
    print(f"--- Teste de Bartlett ({y_var}) ---")
    print(f"Estatística: {bartlett_stat:.4f}, p-value: {bartlett_p:.4e}")[cite: 5]

    if shapiro_p > 0.05 and bartlett_p > 0.05:[cite: 5]
        print("\nResumo da ANOVA (Pressupostos atendidos):")
        anova_table = sm.stats.anova_lm(model, typ=1)
        print(anova_table)[cite: 5]
    else:
        print("Pressupostos não atendidos. Não foi possível realizar a ANOVA.")[cite: 5]

def grupos_media(cultivo, variavel, df, label):
    """Gera a média agrupada por tratamento para um cultivo específico"""
    sub_df = df[df['cult'] == cultivo][cite: 5]
    resumo = sub_df.groupby('trat', observed=False)[variavel].mean().reset_name(label if hasattr(pd.Series, 'reset_name') else 'value')
    resumo = sub_df.groupby('trat', observed=False)[variavel].mean().reset_index()
    resumo.columns = ['trat', label][cite: 5]
    return resumo

def eficiencia_relativa(x, dat):
    """Calcula a Eficiência Relativa com base na MSPA"""
    controle = dat.loc[dat['trat'] == "Controle", 'mspa'].values[0][cite: 5]
    stp = dat.loc[dat['trat'] == "STP", 'mspa'].values[0][cite: 5]
    return np.round((x - controle) * 100 / (stp - controle), 2)[cite: 5]

def eficiencia_fosforo(x, dat):
    """Calcula a Eficiência de Uso de Fósforo com base no AP"""
    controle = dat.loc[dat['trat'] == "Controle", 'ap'].values[0][cite: 5]
    stp = dat.loc[dat['trat'] == "STP", 'ap'].values[0][cite: 5]
    return np.round((x - controle) * 100 / (stp - controle), 2)[cite: 5]


# --- Análise Estatística (MSPA) ---
dapri = dados[dados['cult'] == "Primeiro"].copy()[cite: 5]
daseg = dados[dados['cult'] == "Segundo"].copy()[cite: 5]
dac = dados[dados['cult'] == "Acumulado"].copy()[cite: 5]

# Execução das validações de pressupostos (Dados brutos vs Transformados por log)
for df_part in [dapri, daseg, dac]:
    pressupostos(df_part, 'mspa', 'trat')[cite: 5]
    df_part['log_mspa'] = np.log(df_part['mspa'])[cite: 5]
    pressupostos(df_part, 'log_mspa', 'trat')[cite: 5]


# --- Atribuição Manual de Grupos do Teste de Médias (MSPA) ---
def get_teste_mspa(row):
    t, c = row['trat'], row['cult'][cite: 5]
    if c == "Primeiro":[cite: 5]
        if t in ["BoneChar", "STP", "Bayóvar", "Argélia"]: return "a"[cite: 5]
        if t in ["Marrocos", "Digestato", "Registro", "Arraias", "Catalão"]: return "b"[cite: 5]
        if t in ["Pratápolis", "Bonito", "Controle"]: return "c"[cite: 5]
    elif c == "Segundo":[cite: 5]
        if t in ["BoneChar", "STP", "Marrocos", "Digestato", "Registro"]: return "a"[cite: 5]
        if t in ["Bayóvar", "Argélia", "Arraias", "Catalão", "Pratápolis", "Bonito"]: return "b"[cite: 5]
        if t in ["Controle"]: return "c"[cite: 5]
    elif c == "Acumulado":[cite: 5]
        if t in ["BoneChar", "STP"]: return "a"[cite: 5]
        if t in ["Bayóvar", "Argélia"]: return "b"[cite: 5]
        if t in ["Marrocos", "Digestato", "Registro"]: return "c"[cite: 5]
        if t in ["Arraias", "Catalão"]: return "d"[cite: 5]
        if t in ["Pratápolis", "Bonito"]: return "e"[cite: 5]
        if t in ["Controle"]: return "f"[cite: 5]
    return str(t)[cite: 5]

dados['teste'] = dados.apply(get_teste_mspa, axis=1)[cite: 5]

# Criando dataframe resumo para rótulos nos gráficos da MSPA
dados_resumo = dados.groupby(['trat', 'cult'], observed=False).agg(
    mean_mspa=('mspa', 'mean'),
    teste=('teste', 'first')
).reset_index()[cite: 5]
dados_resumo['label'] = dados_resumo.apply(lambda r: f"{r['mean_mspa']:.2f}{r['teste']}", axis=1)[cite: 5]


# --- Gráficos para MSPA ---
# 1. Boxplot MSPA
fig, axes = plt.subplots(3, 1, figsize=(10, 16), sharex=True)
facets_titles = ["First crop", "Second crop", "Accumulated in two crops"][cite: 5]

for i, cult in enumerate(cult_levels):
    sub_data = dados[dados['cult'] == cult][cite: 5]
    sns.boxplot(data=sub_data, x='trat', y='mspa', hue='teste', ax=axes[i],
                palette=cores, linewidth=0.8, flierprops={"markersize": 4}, legend=False)[cite: 5]
    # Adicionando a média como ponto geométrico
    sns.pointplot(data=sub_data, x='trat', y='mspa', estimator=np.mean, errorbar=None,
                  ax=axes[i], color='black', markers="o", linestyles="", markersize=8)[cite: 5]
    axes[i].set_title(facets_titles[i], loc='left', fontsize=14)[cite: 5]
    axes[i].set_ylabel("Shoot dry mass (g/pot)")[cite: 5]
    axes[i].set_xlabel("")
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

axes[2].set_xticklabels(eixo_x_labels, rotation=0)[cite: 5]
axes[2].set_xlabel("Treatments")[cite: 5]
plt.tight_layout()
plt.savefig("box_mspa.png", dpi=150)[cite: 5]
plt.close()

# 2. Diagrama de Pontos MSPA (Coord Flip)
fig, axes = plt.subplots(3, 1, figsize=(11, 16))
for i, cult in enumerate(cult_levels):
    sub_data = dados[dados['cult'] == cult][cite: 5]
    sub_resumo = dados_resumo[dados_resumo['cult'] == cult][cite: 5]

    sns.scatterplot(data=sub_data, y='trat', x='mspa', hue='teste', ax=axes[i], palette=cores, alpha=0.6, s=100, legend=False)[cite: 5]
    sns.scatterplot(data=sub_resumo, y='trat', x='mean_mspa', ax=axes[i], color='black', marker='s', s=60, legend=False)[cite: 5]

    # Inserção de rótulos textuais das médias + letras
    for _, row in sub_resumo.iterrows():
        axes[i].text(row['mean_mspa'] + 0.8, row['trat'], row['label'], va='center', ha='left', fontweight='bold', fontsize=10)[cite: 5]

    axes[i].set_title(facets_titles[i], loc='left', fontsize=14)[cite: 5]
    axes[i].set_xlabel("Shoot dry mass (g/pot)")[cite: 5]
    axes[i].set_ylabel("Treatments")
    axes[i].set_yticklabels(eixo_x_labels)[cite: 5]
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

plt.tight_layout()
plt.savefig("d_mspa.png", dpi=150)[cite: 5]
plt.close()


# --- Análise Estatística (AP) ---
for df_part in [dapri, daseg, dac]:
    pressupostos(df_part, 'ap', 'trat')[cite: 5]
    df_part['log_ap'] = np.log(df_part['ap'])[cite: 5]
    pressupostos(df_part, 'log_ap', 'trat')[cite: 5]

# Atribuição Manual de Grupos do Teste de Médias (AP)
def get_teste_ap(row):
    t, c = row['trat'], row['cult'][cite: 5]
    if c == "Primeiro":[cite: 5]
        if t in ["BoneChar", "STP", "Bayóvar", "Argélia"]: return "a"[cite: 5]
        if t in ["Marrocos", "Digestato", "Registro", "Arraias"]: return "b"[cite: 5]
        if t in ["Catalão", "Pratápolis"]: return "c"[cite: 5]
        if t in ["Bonito"]: return "d"[cite: 5]
        if t in ["Controle"]: return "e"[cite: 5]
    elif c == "Segundo":[cite: 5]
        if t in ["BoneChar", "STP", "Marrocos", "Digestato", "Registro"]: return "a"[cite: 5]
        if t in ["Bayóvar", "Argélia", "Arraias", "Catalão", "Pratápolis", "Bonito"]: return "b"[cite: 5]
        if t in ["Controle"]: return "c"[cite: 5]
    elif c == "Acumulado":[cite: 5]
        if t in ["BoneChar"]: return "a"[cite: 5]
        if t in ["STP", "Bayóvar", "Argélia"]: return "b"[cite: 5]
        if t in ["Marrocos", "Digestato", "Registro"]: return "c"[cite: 5]
        if t in ["Arraias", "Catalão"]: return "d"[cite: 5]
        if t in ["Pratápolis", "Bonito"]: return "e"[cite: 5]
        if t in ["Controle"]: return "f"[cite: 5]
    return str(t)[cite: 5]

dados['testep'] = dados.apply(get_teste_ap, axis=1)[cite: 5]

dados_resumop = dados.groupby(['trat', 'cult'], observed=False).agg(
    mean_ap=('ap', 'mean'),
    testep=('testep', 'first')
).reset_index()[cite: 5]
dados_resumop['label'] = dados_resumop.apply(lambda r: f"{r['mean_ap']:.2f}{r['testep']}", axis=1)[cite: 5]


# --- Gráficos para AP ---
# 1. Boxplot AP
fig, axes = plt.subplots(3, 1, figsize=(10, 16), sharex=True)
for i, cult in enumerate(cult_levels):
    sub_data = dados[dados['cult'] == cult][cite: 5]
    sns.boxplot(data=sub_data, x='trat', y='ap', hue='testep', ax=axes[i],
                palette=cores, linewidth=0.8, flierprops={"markersize": 4}, legend=False)[cite: 5]
    sns.pointplot(data=sub_data, x='trat', y='ap', estimator=np.mean, errorbar=None,
                  ax=axes[i], color='black', markers="o", linestyles="", markersize=8)[cite: 5]
    axes[i].set_title(facets_titles[i], loc='left', fontsize=14)[cite: 5]
    axes[i].set_ylabel("Shoot phosphorus accumulation (mg/pot)")[cite: 5]
    axes[i].set_xlabel("")
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

axes[2].set_xticklabels(eixo_x_labels, rotation=0)[cite: 5]
axes[2].set_xlabel("Treatments")[cite: 5]
plt.tight_layout()
plt.savefig("box_apa.png", dpi=150)[cite: 5]
plt.close()

# 2. Diagrama de Pontos AP
fig, axes = plt.subplots(3, 1, figsize=(11, 16))
for i, cult in enumerate(cult_levels):
    sub_data = dados[dados['cult'] == cult][cite: 5]
    sub_resumo = dados_resumop[dados_resumop['cult'] == cult][cite: 5]

    sns.scatterplot(data=sub_data, y='trat', x='ap', hue='testep', ax=axes[i], palette=cores, alpha=0.6, s=100, legend=False)[cite: 5]
    sns.scatterplot(data=sub_resumo, y='trat', x='mean_ap', ax=axes[i], color='black', marker='s', s=60, legend=False)[cite: 5]

    for _, row in sub_resumo.iterrows():
        axes[i].text(row['mean_ap'] + 0.8, row['trat'], row['label'], va='center', ha='left', fontweight='bold', fontsize=10)[cite: 5]

    axes[i].set_title(facets_titles[i], loc='left', fontsize=14)[cite: 5]
    axes[i].set_xlabel("Shoot phosphorus accumulation (mg/pot)")[cite: 5]
    axes[i].set_ylabel("Treatments")
    axes[i].set_yticklabels(eixo_x_labels)[cite: 5]
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

plt.tight_layout()
plt.savefig("d_apa.png", dpi=150)[cite: 5]
plt.close()


# --- Cálculo dos Índices de Eficiência ---
media_pri = grupos_media("Primeiro", "mspa", dados, "mspa")[cite: 5]
media_pri['efi_rel'] = eficiencia_relativa(media_pri['mspa'], media_pri)[cite: 5]

media_seg = grupos_media("Segundo", "mspa", dados, "mspa")[cite: 5]
media_seg['efi_rel'] = eficiencia_relativa(media_seg['mspa'], media_seg)[cite: 5]

media_acu = grupos_media("Acumulado", "mspa", dados, "mspa")[cite: 5]
media_acu['efi_rel'] = eficiencia_relativa(media_acu['mspa'], media_acu)[cite: 5]

medip_pri = grupos_media("Primeiro", "ap", dados, "ap")[cite: 5]
medip_pri['efi_pho'] = eficiencia_fosforo(medip_pri['ap'], medip_pri)[cite: 5]

medip_seg = grupos_media("Segundo", "ap", dados, "ap")[cite: 5]
medip_seg['efi_pho'] = eficiencia_fosforo(medip_seg['ap'], medip_seg)[cite: 5]

mediap_acu = grupos_media("Acumulado", "ap", dados, "ap")[cite: 5]
mediap_acu['efi_pho'] = eficiencia_fosforo(mediap_acu['ap'], mediap_acu)[cite: 5]


# --- Consolidação das Tabelas de Eficiência (Equivalente ao bind_rows) ---
media_pri['cult'] = "Primeiro"[cite: 5]
media_acu['cult'] = "Acumulado"[cite: 5]
dados_ea = pd.concat([media_pri, media_acu], ignore_index=True)[cite: 5]
dados_ea['cult'] = pd.Categorical(dados_ea['cult'], categories=["Primeiro", "Acumulado"], ordered=True)[cite: 5]

medip_pri['cult'] = "Primeiro"[cite: 5]
mediap_acu['cult'] = "Acumulado"[cite: 5]
dados_ep = pd.concat([medip_pri, mediap_acu], ignore_index=True)[cite: 5]
dados_ep['cult'] = pd.Categorical(dados_ep['cult'], categories=["Primeiro", "Acumulado"], ordered=True)[cite: 5]


# --- Geração dos Gráficos de Barras de Eficiência ---
# 1. Gráfico Eficiência Relativa (fig_ea)
fig, axes = plt.subplots(1, 2, figsize=(12, 6), sharey=True)
titles_ea = ["First crop", "Accumulated in two crops"][cite: 5]

for i, cult in enumerate(["Primeiro", "Acumulado"]):[cite: 5]
    sub_ea = dados_ea[dados_ea['cult'] == cult].copy()[cite: 5]
    # Reordenando baseado no efi_rel
    sub_ea = sub_ea.set_index('trat').reindex(trat_levels).reset_index()

    sns.barplot(data=sub_ea, y='trat', x='efi_rel', ax=axes[i], color="#9e2943", alpha=0.6)[cite: 5]

    # Adicionando rótulos numéricos nas barras
    for _, row in sub_ea.iterrows():
        val = row['efi_rel']
        hjust = val - 4 if val > 0 else val + 1
        axes[i].text(hjust, row['trat'], f"{val:.0f}", va='center', ha='right' if val > 0 else 'left', fontsize=11)[cite: 5]

    axes[i].set_title(titles_ea[i], fontsize=12)[cite: 5]
    axes[i].set_xlabel("Relative efficiency (%)")[cite: 5]
    axes[i].set_ylabel("Treatments" if i == 0 else "")
    if i == 0:
        axes[i].set_yticklabels(eixo_x_labels)[cite: 5]
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

plt.tight_layout()
plt.savefig("fig_ea.png", dpi=150)[cite: 5]
plt.close()

# 2. Gráfico Eficiência de Fósforo (fig_ep)
fig, axes = plt.subplots(1, 2, figsize=(12, 6), sharey=True)

for i, cult in enumerate(["Primeiro", "Acumulado"]):[cite: 5]
    sub_ep = dados_ep[dados_ep['cult'] == cult].copy()[cite: 5]
    sub_ep = sub_ep.set_index('trat').reindex(trat_levels).reset_index()

    sns.barplot(data=sub_ep, y='trat', x='efi_pho', ax=axes[i], color="#d18525", alpha=0.6)[cite: 5]

    for _, row in sub_ep.iterrows():
        val = row['efi_pho']
        # Lógica de posicionamento do texto correspondente ao script R
        if val >= 0.5: ha, adj = 'right', val - 3
        elif val > 0: ha, adj = 'right', val - 0.5
        else: ha, adj = 'left', val + 0.5
        axes[i].text(adj, row['trat'], f"{val:.0f}", va='center', ha=ha, fontsize=11)[cite: 5]

    axes[i].set_title("", fontsize=12)[cite: 5]
    axes[i].set_xlabel("P use efficiency (%)")[cite: 5]
    axes[i].set_ylabel("Treatments" if i == 0 else "")
    if i == 0:
        axes[i].set_yticklabels(eixo_x_labels)[cite: 5]
    axes[i].set_facecolor('whitesmoke')
    axes[i].grid(True, linestyle=':', color='grey', alpha=0.6)

plt.tight_layout()
plt.savefig("fig_ep.png", dpi=150)[cite: 5]
plt.close()